import { IUser } from '../entities/user';
import { IConfig } from '../services/config';
import { UserDragAction } from '../directives/draggable-user';
import { NotificationType } from '../keys/notification-type';
import { LoginMode } from '../keys/login-mode-keys';
import { MessageType } from '../keys/message-type';

export interface IRootScope extends ng.IRootScopeService {
  auth: any;
  config: IConfig;
  disableDrag: boolean;
  loginMode: LoginMode;
  loginURL: string;
  messageTypeFile: MessageType;
  messageTypeImage: MessageType;
  messageTypeText: MessageType;
  partialsURL: string;
  registerURL: string;
  user: IUser;
  userDrag: UserDragAction;
  websiteName: string;
  img_20_cross: string;
  img_20_flag: string;
  img_20_flagged: string;
  img_20_friend: string;
  img_20_user: string;
  img_24_copy: string;
  img_24_cross: string;
  img_24_save: string;
  img_25_drag: string;
  img_30_cache_cleared: string;
  img_30_clear_cache: string;
  img_30_cross: string;
  img_30_emojis: string;
  img_30_gear: string;
  img_30_image: string;
  img_30_logout: string;
  img_30_maximize: string;
  img_30_minimize: string;
  img_30_plus: string;
  img_30_powered_by: string;
  img_30_profile_pic: string;
  img_30_resize: string;
  img_30_save: string;
  img_30_shutdown_on: string;
  img_30_shutdown: string;
  img_30_sound_off: string;
  img_30_sound_on: string;
  img_30_start_chatting: string;
  img_40_cross: string;
  img_40_tick: string;
  img_file_aac: string;
  img_file_acc: string;
  img_file_ai: string;
  img_file_avi: string;
  img_file_bmp: string;
  img_file_download: string;
  img_file_f4a: string;
  img_file_gif: string;
  img_file_html: string;
  img_file_jpeg: string;
  img_file_jpg: string;
  img_file_jpp: string;
  img_file_json: string;
  img_file_m4a: string;
  img_file_midi: string;
  img_file_mov: string;
  img_file_mp3: string;
  img_file_mp4: string;
  img_file_oga: string;
  img_file_ogg: string;
  img_file_pdf: string;
  img_file_psd: string;
  img_file_rtf: string;
  img_file_svg: string;
  img_file_tif: string;
  img_file_tiff: string;
  img_file_txt: string;
  img_file_wav: string;
  img_file_wma: string;
  img_file_xml: string;
  img_file_zip: string;
  img_file: string;
  img_loader: string;
  showNotification(type: NotificationType, title: string, message?: string, button?: string): void;
}
